services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/swift_codes
      SPRING_DATASOURCE_USERNAME: admin1
      SPRING_DATASOURCE_PASSWORD: qwe123
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=swift_codes'
      - 'POSTGRES_USER=admin1'
      - 'POSTGRES_PASSWORD=qwe123'
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin1 -d swift_codes"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


volumes:
  postgres_data: